### ISSUE TITLE
[Fix Request] 회원 가입 API 수정 요청

### ISSUE THREAD

**Issue by ZinnaChoi** [ZinnaChoi/Study-Management#27]
안녕하세요 @MeMyself-And-I !

> POST /api/v1/join

### 1. 중복 ID 요청 시 에러 처리 수정 요청

> 만약 중복 조회 API가 실행 된 이후에 회원 가입이 실행되는 것이 반드시 보장된다면 이는 필수 수정사항은 아닙니다

- 회원가입 API에서 동일 ID로 (DB에 이미 존재하는 ID로) 회원가입 요청 시, DB 쿼리 수행 중에 에러가 발생해 500에러가 발생합니다
- DUPLICATED 에러 코드 생성 후 에러 처리 추가 부탁드립니다!
![image](https://github.com/ZinnaChoi/Study-Management/assets/142554606/c345927f-01fc-44da-bbb3-532dd4c8049c)

### 2.  Input 수정 요청
- 또한 특정 사람의 스터디 타임 입력 시 (eventName) 여러 개의 event를 등록 할 수 있어야 할 것 같습니다 이 부분도 확인 후 적절한 형태로 변경 부탁드립니다!!

```json
{
  "sendDate": "20240112113804899",
  "systemId": "STUDY_0001",
  "id": "zinna",
  "password": "...!",
  "name": "ZinnaChoi",
  "contact": "01011112222",
  "studyName": "모각코 스터디",
  "eventName": "1PM",
  "wakeupTime": "0730"
}

```
![image](https://github.com/ZinnaChoi/Study-Management/assets/142554606/2ef0e6a7-a7ce-4606-8e57-442afd1a64ca)

감사합니다

**Comment by MeMyself-And-I** [comment]
1번 사항의 경우 아이디 중복 조회 API가 실행 된 이후에 회원 가입이 실행되는 것이 반드시 보장됩니다!
보통 홈페이지 회원가입 페이지들이 그렇게 구현되어있더라구요! 참조해서 동일하게 적용하려고 합니다.
2번 사항은 수정후 커밋 내역 링크 공유 하겠습니다.

**Comment by MeMyself-And-I** [comment]
2번 사항 이슈 수정하여 PR 드렸습니다 하기는 관련 작업 내역 링크 입니다.
https://github.com/ZinnaChoi/Study-Management/pull/32/commits/0fbf8b765ebbe0ee09e5069b8684f0274bc49262
