### ISSUE TITLE
[Fix Request] 멤버 검색 시 범위, 부분 검색 기능 추가 요청

### ISSUE THREAD

**Issue by ZinnaChoi** [ZinnaChoi/Study-Management#51]
아래 PR에서 언급한 것처럼 멤버 검색 시 범위, 부분 검색이 가능하도록 개선하면 좋을 것 같아요!

https://github.com/ZinnaChoi/Study-Management/pull/37

**Comment by MeMyself-And-I** [comment]
> 아래 PR에서 언급한 것처럼 멤버 검색 시 범위, 부분 검색이 가능하도록 개선하면 좋을 것 같아요!
> 
> 이벤트 이름으로 멤버 찾을 때와 기상 시간으로 멤버 찾을 때 == (equal) 검색 보다는 부분 like 검색, 범위 검색이 더 유용할 것 같아요! 이벤트 이름 같은 경우는 like 검색, 기상시간은 (이상/이하) 그리고 기준(오전8시) 를 받아서 버뮈 검색으로 바꾸는 건 어떤가요? 쿼리가 너무 복잡해 진다면 JPA specification을 사용하면 조금 간단하게 할 수 있을 것 같아용 👍
> 
> #37

https://github.com/ZinnaChoi/Study-Management/pull/47#discussion_r1466387196

**Comment by MeMyself-And-I** [comment]
최종 화면 설계 방안
https://github.com/ZinnaChoi/Study-Management/pull/84

**Comment by MeMyself-And-I** [comment]
이슈 해결 완료
https://github.com/ZinnaChoi/Study-Management/pull/95

**Comment by ZinnaChoi** [comment]
이슈 확인되어 close 하겠습니다~

**Comment by ZinnaChoi** [comment]
이슈 확인되어 close 하겠습니다~
