### ISSUE TITLE
[Fix Request] 부재 일정 등록 시 네트워크 관련 이슈

### ISSUE THREAD

**Issue by dayeon-dayeon** [ZinnaChoi/Study-Management#77]
부재 일정 등록 시 
등록은 성공적으로 되나  '부재 일정 등록 Unknown error' alart 창이 뜨는 에러로

네트워크가 원활하지 않은 환경에서
response가 오는 시간이 더뎌 발생하는 상황으로 추측됩니다.
기능 동작에는 문제가 없어 merged 합니다. 
해당 이슈 추후에 수정 요청드립니다 !

https://github.com/ZinnaChoi/Study-Management/pull/74

**Comment by ZinnaChoi** [comment]
안녕하세요! 

정리하자면 다연씨의 로컬 환경에서
| 구분 | 기능 동작 여부 |  retMsg 수신 여부 |
| -- | -- | -- |
| Swagger API Test | O | O |
| UI Test | O | X | 

이러한 상황인거죠?
하지만 네트워크가 아예 안되는(기능조차 정상 동작하지 않는) 상황이 아니다보니 제가 재현하고, 테스트하기가 어려운 상황입니다!

만약 해당 이슈가 실제로 존재한다면, 다연씨 그리고 찬혁씨가 각자 맡은 기능을 개발할 때도 다연씨의 로컬 환경에서 동일 이슈가 발생할 것이니 다연씨가 디버깅을 해야 할 것 같아요

물론 기능 개발 후에 진행하셔도 괜찮습니다!

일시적인 오류였거나  제 담당 기능(게시판, 부재일정)에서만 이슈가 발생한다면 다시 언급해주시길 바랍니다!

감사합니다

**Comment by ZinnaChoi** [comment]
@dayeon-dayeon 다연씨 개인 로컬 이슈로 확인되어 종료하겠습니다 ~
